### ISSUE TITLE
Design Documents

### ISSUE THREAD

**Issue by trevoruptain** [catly1/moefy#1]
Hey Carlos! I've been using Spotify a lot lately, and I think this is going to be a great project - there are going to be a lot of fun features to implement. 

I have a few suggestions for your proposal:

Schema:

- [x]  Songs should have a 'name' and a 'song_url'
- [x] Albums need a 'name' and a 'year'

State Shape:

- [x] Don't forget to include 'ui', 'errors', and 'session' outside of the entities object. See the sample proposal (https://github.com/appacademy/bluebird/wiki/sample-state)
- [x] albums and artists need an 'image_url'

Your state shape looks good and it seems like you put some thought into it. Great work.

**Comment by catly1** [comment]
Spotify certainly charged the way I listen to music!

Gonna put those columns and objects in.

**Comment by trevoruptain** [comment]
Your proposal is great - there isn't much to add here since it's nearly perfect. I think you just need a frontend route for a song - doesn't Spotify have some kind of Song Detail component?

**Comment by catly1** [comment]
The webapp has no options to show the credits/details of a song but the phone and desktop app lets you. I'll add them in. The song does have its own route but when you go to it it links to the album's show page.

**Comment by catly1** [comment]
Some songs also have multiple artist working on them so I gotta make a joins table.
